#Configuracion del Menu
#Sat Feb 28 23:48:30 VET 2026
desayuno_precio=$ 1000
precio_0=$36000
almuerzo_precio=$ 0.00
almuerzo_nombre=Almuerzo
desayuno_nombre=Desayuno
nombre_0=pasta
imagen_0=C\:\\Users\\wilber_2\\Desktop\\proyecto-comedor-2-2025-grupo-12\\imagenes_menu\\platillo_0_1772029599586.jpg
desayuno_imagen=C\:\\Users\\hanli\\Desktop\\repo-correci-n-comedor-ucv\\imagenes_menu\\platillo_0_1772336905288.jpg
almuerzo_imagen=/com/comedor/resources/images/menu/base.jpg
ccb_actual=7.15
