#Actualizacion de Costos (CCB) y Tarifas
#Mon Mar 09 14:47:48 VET 2026
almuerzo_descripcion=
almuerzo_imagen=C\:\\Users\\hanli\\Desktop\\repo-correci-n-comedor-ucv\\imagenes_menu\\platillo_0_1772028112963.jpg
almuerzo_nombre=Almuerzo
almuerzo_nutricion=
almuerzo_precio=$ 4000
ccb_actual=1.04
desayuno_descripcion=Hola no s\u00E9 esto es un test
desayuno_imagen=C\:\\Users\\hanli\\Desktop\\repo-correci-n-comedor-ucv\\imagenes_menu\\platillo_0_1772336905288.jpg
desayuno_nombre=Desayuno
desayuno_nutricion=guevo 100%
desayuno_precio=$ 1000
imagen_0=C\:\\Users\\wilber_2\\Desktop\\proyecto-comedor-2-2025-grupo-12\\imagenes_menu\\platillo_0_1772029599586.jpg
nombre_0=pasta
precio_0=$36000
tarifa_pct_empleado=92.0
tarifa_pct_estudiante=26.0
tarifa_pct_profesor=80.0
