#Configuracion del Menu
#Wed Mar 11 21:34:55 VET 2026
desayuno_precio=$ 1000
almuerzo_nombre=Almuerzo
imagen_0=C\:\\Users\\wilber_2\\Desktop\\proyecto-comedor-2-2025-grupo-12\\imagenes_menu\\platillo_0_1772029599586.jpg
tarifa_pct_estudiante=25.0
precio_0=$36000
almuerzo_precio=$ 4000
almuerzo_descripcion=
desayuno_nombre=Papas 
desayuno_nutricion=hayaca 15%\navena 90%
nombre_0=pasta
tarifa_pct_empleado=108.0
tarifa_pct_profesor=80.0
desayuno_imagen=C\:\\Users\\WinterOS\\Documents\\repo-correci-n-comedor-ucv\\imagenes_menu\\platillo_0_1772028112963.jpg
almuerzo_imagen=C\:\\Users\\hanli\\Desktop\\repo-correci-n-comedor-ucv\\imagenes_menu\\platillo_0_1772028112963.jpg
ccb_actual=0.22000000000000003
desayuno_descripcion=Hola no s\u00E9 esto es un test
almuerzo_nutricion=
